### ISSUE TITLE
Shortcodes!

### ISSUE THREAD

**Issue by bfintal** [gambitph/Page-Builder-Sandwich#17]
*List down all shortcodes created here.*

### Support all these: http://en.support.wordpress.com/category/shortcodes/ plus our own *common* shortcodes (e.g. toggle/faq)

**As much as possible, do not create shortcodes from scratch. Check Jetpack first if they exist already**

Embed shortcodes from http://en.support.wordpress.com/category/shortcodes/ that already work via **Add Media > Insert From URL** should **NOT** be made into a new shortcode since those are already handled by the `embed` shortcode #53 . Those will already work with Shortcake & Sandwich. Instead, document what types of embeds URLs work from there.

**Shortcodes:**
* [ ] icon #35 #152 
* [x] button #21
* [x] embed #53
* [x] self hosted html5 video #54
* [x] remote html5 video #59
* [x] googlemap (Jetpack) #18
* [x] contact form (Jetpack) #19
* [x] toggle #20
* [x] portfolio (Jetpack) #39
* [x] Twitter timeline (Jetpack) #42
* [x] Subscribe (Jetpack) [jetpack_subscription_form](http://jetpack.me/support/subscriptions/)

**Shortcodes that appear only when their plugins are activated**
* [x] Events Manager #63 
* [x] Contact Form 7 #62
* [x] MailChimp for WP #67
* [x] bbPress #64

**Widgets:**
* [ ] Top Posts (Jetpack)
* [x] Archives
* [x] Calendar
* [x] Categories
* [x] Custom Menu
* [x] Meta
* [x] Pages
* [x] Recent Comments
* [x] Recent Posts
* [x] RSS
* [x] Search
* [x] Tag Cloud
* [x] Display WordPress Posts (Jetpack)
* [x] Facebook Like Box (Jetpack)
* [x] Gravatar Profile (Jetpack)
* [x] RSS Links (Jetpack)

**Pro Shortcodes**
* [x] Conditional #87
* [x] WooCommerce (12 shortcodes)
* [x] Easy Digital Downloads
* [x] Gravity Forms
